[package]
name = "test-parachain-halt"
description = "Test parachain which executes forever"
build = "build.rs"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/karanvir12/substrate36.git", branch = "relpeer" }

[features]
default = [ "std" ]
std = []
