# 🔒 PROTECTED: Changes to locks-review-team should be approved by the current locks-review-team
locks-review-team: locks-review
team-leads-team: peer-review
action-review-team: ci

rules:
  - name: Runtime files
    check_type: changed_files
    condition: ^runtime/(|peer)/src/[^/]+\.rs$
    all_distinct:
      - min_approvals: 1
        teams:
          - locks-review
      - min_approvals: 1
        teams:
          - peer-review

  - name: Core developers
    check_type: changed_files
    condition:
      include: .*
      # excluding files from 'Runtime files' and 'CI files' rules
      exclude: ^runtime/(|peer)/src/[^/]+\.rs$|^\.gitlab-ci\.yml|^scripts/ci/.*|^\.github/.*
    min_approvals: 2
    teams:
      - core-devs

  - name: CI files
    check_type: changed_files
    condition:
      include: ^\.gitlab-ci\.yml|^scripts/ci/.*|^\.github/.*
    min_approvals: 2
    teams:
      - ci
      - release-engineering

prevent-review-request:
  teams:
    - core-devs
