[package]
name = "peer-node-primitives"
description = "Primitives types for the Node-side"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
bounded-vec = "0.6"
futures = "0.3.21"
peer-primitives = { path = "../../primitives" }
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/karanvir12/substrate36.git", branch = "relpeer" }
sp-application-crypto = { git = "https://github.com/karanvir12/substrate36.git", branch = "relpeer" }
sp-consensus-vrf = { git = "https://github.com/karanvir12/substrate36.git", branch = "relpeer" }
sp-consensus-babe = { git = "https://github.com/karanvir12/substrate36.git", branch = "relpeer" }
sp-keystore = { git = "https://github.com/karanvir12/substrate36.git", branch = "relpeer" }
sp-maybe-compressed-blob = { git = "https://github.com/karanvir12/substrate36.git", branch = "relpeer" }
peer-parachain = { path = "../../parachain", default-features = false }
schnorrkel = "0.9.1"
thiserror = "1.0.31"
serde = { version = "1.0.137", features = ["derive"] }

[target.'cfg(not(target_os = "unknown"))'.dependencies]
zstd = { version = "0.11.2", default-features = false }

[dev-dependencies]
peer-erasure-coding = { path = "../../erasure-coding" }
