[package]
name = "remote-ext-tests-bags-list"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
polkadot-runtime = { path = "../../../runtime/polkadot" }
polkadot-runtime-constants = { path = "../../../runtime/polkadot/constants" }


pallet-bags-list-remote-tests = { git = "https://github.com/karanvir12/substrate36.git", branch = "relpeer" }
sp-tracing = { git = "https://github.com/karanvir12/substrate36.git", branch = "relpeer" }
frame-system = { git = "https://github.com/karanvir12/substrate36.git", branch = "relpeer" }
sp-core = { git = "https://github.com/karanvir12/substrate36.git", branch = "relpeer" }

clap = { version = "4.0.9", features = ["derive"] }
log = "0.4.17"
tokio = { version = "1.22.0", features = ["macros"] }
