[package]
name = "slot-range-helper"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
paste = "1.0"
enumn = "0.1.5"
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["derive"] }
sp-std = { package = "sp-std", git = "https://github.com/karanvir12/substrate36.git", default-features = false , branch = "relpeer" }
sp-runtime = { git = "https://github.com/karanvir12/substrate36.git", default-features = false , branch = "relpeer" }

[features]
default = ["std"]
std = [
	"sp-std/std",
	"parity-scale-codec/std",
	"sp-runtime/std",
]
